{{- if and .Values.clustering.enabled (not .Values.clustering.encryption.existingSecret) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "reshapr-proxy.fullname" . }}-keystore-gen
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "reshapr-proxy.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "reshapr-proxy.fullname" . }}-keystore-gen
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "reshapr-proxy.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "reshapr-proxy.fullname" . }}-keystore-gen
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "reshapr-proxy.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "reshapr-proxy.fullname" . }}-keystore-gen
subjects:
  - kind: ServiceAccount
    name: {{ include "reshapr-proxy.fullname" . }}-keystore-gen
    namespace: {{ .Release.Namespace }}
{{- end }}
