{{- if not .Values.gateway.controlPlane.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reshapr-proxy.fullname" . }}-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "reshapr-proxy.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.gateway.controlPlane.tokenKey }}: {{ .Values.gateway.controlPlane.token | b64enc | quote }}
{{- end }}
