{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "reshapr-proxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "reshapr-proxy.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "reshapr-proxy.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /q/metrics
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
{{- end }}
