{{- if not .Values.apiKey.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reshapr-ctrl-plane.fullname" . }}-api-key
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "reshapr-ctrl-plane.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.apiKey.key }}: {{ .Values.apiKey.value | b64enc | quote }}
{{- end }}
