{{- if and .Values.authentication.idp.enabled (not .Values.authentication.idp.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reshapr-ctrl-plane.fullname" . }}-idp-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "reshapr-ctrl-plane.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.authentication.idp.clientIdKey }}: {{ .Values.authentication.idp.clientId | b64enc | quote }}
  {{- if .Values.authentication.idp.clientSecret }}
  {{ .Values.authentication.idp.clientSecretKey }}: {{ .Values.authentication.idp.clientSecret | b64enc | quote }}
  {{- end }}
{{- end }}
