{{- if and (not .Values.jwtKeys.existingSecret) (.Values.jwtKeys.privateKey.value) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reshapr-ctrl-plane.fullname" . }}-jwt-keys
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "reshapr-ctrl-plane.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.jwtKeys.privateKey.key }}: {{ .Values.jwtKeys.privateKey.value | b64enc | quote }}
  {{ .Values.jwtKeys.publicKey.key }}: {{ .Values.jwtKeys.publicKey.value | b64enc | quote }}
{{- end }}