{{- if not .Values.encryptionKey.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reshapr-ctrl-plane.fullname" . }}-encryption-key
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "reshapr-ctrl-plane.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.encryptionKey.key }}: {{ .Values.encryptionKey.value | b64enc | quote }}
{{- end }}
