{{- if .Values.admissionController.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "controllers.admission.serviceName" . }}
  labels:
    {{- include "controllers.labels" . | nindent 4 }}
    app.kubernetes.io/component: admission
  {{- if eq .Values.admissionController.certificate.provider "openshift" }}
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: {{ include "controllers.fullname" . }}-admission-tls
  {{- end }}
spec:
  type: {{ .Values.admissionController.service.type }}
  ports:
    - name: http
      port: {{ .Values.admissionController.service.httpPort }}
      targetPort: {{ .Values.admissionController.httpContainerPort }}
      protocol: TCP
    - name: https
      port: {{ .Values.admissionController.service.httpsPort }}
      targetPort: {{ .Values.admissionController.httpsContainerPort }}
      protocol: TCP
  selector:
    {{- include "controllers.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: admission
{{- end }}
